### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by thelazyoneBL** [lukdwo/OpenWRT-collectd-MQTT-HA#1]
Hi,
thanks for your template.
I have some improvements for you.

1. In my case i had to create directory "conf.d" in /etc/collectd/ and put mqtt.conf there, so my OpenWRT wont overwrite it:

/etc/collectd/conf.d/mqtt.conf:
```
LoadPlugin mqtt
<Plugin "mqtt">
  <Publish "RT3200">
    Host "192.168.1.11"
    Port "1883"
    User "RT3200"
    Password "secret password"
    ClientId "RT3200"
    Prefix "collectd"
    Retain true
  </Publish>
</Plugin>
```

User created in HA:
```
    User "RT3200"
    Password "secret password"
```
In Mosquitto broker integration in HA, in configuration, I had to add 
`collectd/#`
to "Listen to a topic".

After that, restart the Mosquito broker on HA, restart collectd on the OpenWRT router via ssh: service collectd restart

2. for "uptime" value_template should have additional ( ) for round() to work:

`value_template: "{{ (value.split(':')[1].split('\x00')[0] | float / 86400) | round(1) }}"`
instead of
`value_template: "{{ value.split(':')[1].split('\x00')[0] | int / 86400 | round(1) }}"`

3. adding device information will create new device in Home Assistant, and put all sensors in it:

Same code for every sensor:
```
    device:
      identifiers: RT3200
      name: Router Belkin RT3200
      model: RT3200
      manufacturer: Belkin
```
```
  # temperature -----------------------------------------------------------------
  - name: RT3200 temperature pci-0100
    state_topic: collectd/RT3200/sensors-mt7915_phy1-pci-0100/temperature-temp1
    unit_of_measurement: °C
    value_template: "{{ value.split(':')[1].split('\x00')[0] | int }}"
    unique_id: RT3200_temp_pci-0100
    device:
      identifiers: RT3200
      name: Router Belkin RT3200
      model: RT3200
      manufacturer: Belkin

  # cpu usage -----------------------------------------------------------------
  - name: RT3200 cpu-0 usage
    state_topic: collectd/RT3200/cpu-0/percent-idle
    unit_of_measurement: "%"
    value_template: "{{ (100-(value.split(':')[1].split('\x00')[0] | float )) | round(2) }}"
    unique_id: RT3200_cpu-0_usage
    device:
      identifiers: RT3200
      name: Router Belkin RT3200
      model: RT3200
      manufacturer: Belkin
```
